PANTHEONtech/YANGinator

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/breadcrumbs/YangBreadcrumbsPresentationProvider.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/breadcrumbs/YangBreadcrumbsProvider.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/breadcrumbs/YangCrumbPresentation.java
intelij-plugin/src/main/resources/META-INF/plugin.xml

Add breadcrumb support

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/YangParserDefinition.java

Adds highlighting of TODO in comments.
resolves #6
note: may not register existing TODOs correctly, invalidating caches should fix it.

Added highlighting for TODO in comments

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/completion/YangPsiTreeChangeListener.java

Changes to prevent NullPointerException in YangPsiTreeChangeListener.
resolves #9

Added improvements to null checking in YangPsiTreeChangeListener.

---

build.gradle

Release 1.0

---

intelij-plugin/build.gradle

Fix publish token variable name

---

build.gradle

Release 1.1

---

build.gradle

Make SNAPSHOT version

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/reference/YangReference.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/reference/YangUtil.java

Signed-off-by: ivan.martiniak <ivan.martiniak@pantheon.tech>

Class Cast Exception Fixed

---

README.md
intelij-plugin/src/main/resources/META-INF/plugin.xml

Update for change notes and features.
resolves #28

Cleanup before 1.2 release

---

intelij-plugin/src/test/testData/parser/ParsingTestData.yang

Added testing for improved type statement

---

build.gradle

Setup release tasks

---

.github/workflows/release.yml

Setup new release action

---

intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/parser/YangParser.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/YangGrammar.bnf

Added proper checking for identifier start character.
resolves #10

properly checking identifier start character

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/breadcrumbs/YangBreadcrumbsProvider.java

Added breadcrumbs support for grouping.
resolves #38

Added breadcrumbs support for grouping

---

intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/parser/YangParser.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/YangModuleStmt.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/YangSubmoduleStmt.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/impl/YangModuleStmtImpl.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/impl/YangSubmoduleStmtImpl.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/YangGrammar.bnf

Changes to grammar so PSI structure is easier to work with.
resolves #47 

Grammar change to allow proper working of formatter

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/formatter/YangFormattingModelBuilder.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/formatter/settings/YangCodeStyleMainPanel.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/formatter/settings/YangCodeStyleSettings.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/formatter/settings/YangCodeStyleSettingsProvider.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/formatter/settings/YangLanguageCodeStyleSettingsProvider.java
intelij-plugin/src/main/resources/META-INF/plugin.xml
intelij-plugin/src/main/resources/codeStyle/preview/preview.yang

Added code style setting for yang formatting.
resolves #46 

Added code style settings fo yang

---

intelij-plugin/build.gradle
intelij-plugin/src/main/resources/META-INF/plugin.xml

Fix compatibility issues with older and newer versions

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/external/AnyOrderRuleTutorial.md
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/external/ExternalRules.java
intelij-plugin/src/main/resources/META-INF/plugin.xml

-add documentation description how it works
-comment annotator in plugin.xml
Signed-off-by: tobias.pobocik <tobias.pobocik@pantheon.tech>

Add AnyOrder external rule

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/external/ExternalRules.java

Signed-off-by: Jan Purdek <jan.purdek@pantheon.tech>

added external rules checkString and checkChar

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/completion/YangCompletionContributorBuilder.java

Signed-off-by: Cmarada, Michal <michal.cmarada@pantheon.tech>

fix NPE in YangCompletionContributorBuilder

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/completion/YangCompletionContributorPopUp.java

Complition Contributor PopUp fix

---

.github/workflows/release.yml

#65 Release action fix

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/reference/YangUtil.java

Signed-off-by: Jan Purdek <jan.purdek@pantheon.tech>

Fixed reference for quoted-identifiers

---

intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/YangGrammar.bnf
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/lexer/_YangLexer.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/parser/YangParser.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/YangPatternBody.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/YangTypes.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/YangVisitor.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/impl/YangPatternBodyImpl.java
intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/impl/YangPatternStmtImpl.java
rfc-parser/src/main/java/tech/pantheon/yanginator/parser/services/GrammarKitRFCUncomplaintUtils.java

Adding method to change pattern expression in Bnf

---

build.gradle

Editing Gradle Tasks

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/formatter/YangFormattingModelBuilder.java

#119 Formatting buf Fixed, braces already formatting correctly

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/YangAnnotator.java

Signed-off-by: filip.vitkovsky <filip.vitkovsky@pantheon.tech>

Add additional validation for root element of Yang file #150

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/formatter/YangFormattingModelBuilder.java

Signed-off-by: Filip Vitkovský <filip.vitkovsky@pantheon.tech>

Added spacing around curly braces

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/formatter/settings/YangCodeStyleSettings.java

Signed-off-by: Filip Vitkovský <filip.vitkovsky@pantheon.tech>

Fixed NSFexception for code style settings

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/formatter/YangFormatterUtils.java

Signed-off-by: peter.ivanic <peter.ivanic@pantheon.tech>

fix unknown statements offset.

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/element/YangListStmtCheck.java

already done, but then accidentally overwritten by another change

list-stmt anotator fix for data-def-stmt

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/YangAnnotator.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/check/ImportIncludeCheck.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/element/YangImportStmtCheck.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/element/YangIncludeStmtCheck.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/element/YangPrefixStmtCheck.java

Added checks for prefix, include and import statements

251 add check for import and include statements possible validation enhancement

---

intelij-plugin/build.gradle
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/YangAnnotator.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/element/YangKeyStmtCheck.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/annotator/element/YangSubmoduleStmtCheck.java
intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/reference/YangUtil.java

- fix duplicity of filtering
- change file path getter
- clean up code in keyStmtCheck.java
- fix annotator submodule checks
- add runIde task with defined RAM

Fix getVirtualFiles slow operation and cleanup code

---

gradle.properties
intelij-plugin/build.gradle

- bump the version to 2.5.0
- reduce plugin check versions to recommended only

Bump Intellij Platform plugin version

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/highlighter/YangPairedCurlyBraceMatcher.java

We fixed the bug with the correct YangType

Bugfix for curly braces

---

intelij-plugin/src/main/java/tech/pantheon/yanginator/plugin/breadcrumbs/YangBreadcrumbsProvider.java

https://github.com/PANTHEONtech/YANGinator/issues/315

leaf-list not showing in breadcrumbs bugfix

---

intelij-plugin/build.gradle

Verify plugin only against IntelliJ IDEA Community Edition.

Fix: build fails because of low disk space
